### ISSUE TITLE
Cannot specialize non-generic type 'Optional'

### ISSUE THREAD

**Issue by optimusbits** [3D4Medical/glTFSceneKit#1]
line 115 : `case Optional<Any>.none:` in file JSONCodingKeys.swift causes compilation error `Cannot specialize non-generic type 'Optional'`

**Comment by sakrist** [comment]
@pkalinowski  which swift version?

**Comment by optimusbits** [comment]
I set in Build Settings > Swift Language version - Swift 4.1

**Comment by sakrist** [comment]
Does it resolve your issue or it's still on?

**Comment by optimusbits** [comment]
No, I have this settigns from the beginning

**Comment by sakrist** [comment]
Fixed for now. You did not mention in first place that it's on encoding :)

**Comment by optimusbits** [comment]
Thanks
