### ISSUE TITLE
How to add this package in existing Xcode project ? 

### ISSUE THREAD

**Issue by AlexPiro** [3D4Medical/glTFSceneKit#2]
I try to install this package in my existing Xcode project ?
How do you install it ? Swift package manager seems to not work with iOS in Xcode 10.
I try to build it but I got errors ...

Thank you for your help

macOS 10.14.6
Xcode 10.3

**Comment by 3d4m-volodymyr** [comment]
Yes, last update was year ago. We will do update once Xcode 11 fully out.
It's still 4.0 package manager. Meantime you can drop Xcode project into your project and configure build dependencies.

**Comment by AlexPiro** [comment]
Thank you very much for this quick answer.
I finally managed to get this working ! 
For those who are in my case : 
1. Download this project and the Draco swift package
2. Drag both xcodeproj in your current project
3. Add GltfSceneKit.framework (which correspond to your platform) in your project librairies
4. Build !
